lzc-sdk-version: 0.1
name: JDownloader2
package: anpho.lzcapp.jdownloader2
version: 25.2.1
description: JDownloader 2 is a free, open-source download management tool with a huge community of developers that makes downloading as easy and fast as it should be. Users can start, stop or pause downloads, set bandwith limitations, auto-extract archives and much more. 
license: https://choosealicense.com/licenses/mit/
homepage: https://jdownloader.org/
author: anpho
application:
  multi_instance: true
  background_task: true
  routes:
    - /=http://jdownloader2.anpho.lzcapp.jdownloader2.lzcapp:5800
  subdomain: jdownloader2
services:
  jdownloader2:
    image: registry.lazycat.cloud/anpho/jlesage/jdownloader-2:166efdaaa490934d
    # lzc-cli  appstore copy-image jlesage/jdownloader-2:latest
    binds:
      - /lzcapp/var/data:/config
      - /lzcapp/run/mnt/home/jdownloader2:/output